language: python

python:
  - "3.6"

before_install:
  - pip install codecov
  - pip install pytest==4.3.0
  - pip install pytest-cov

# command to install dependencies
install: true

# command to run tests
script:
  - pytest --cov=./

after_success:
  - codecov
